### ISSUE TITLE
About Lmpatch

### ISSUE THREAD

**Issue by yurilove** [pmrowla/pylivemaker#82]
### Description
Hi，I'm trying to Lmpatch mutiple lsb files back to a exe file,but I don' know how to use the option -r.
Could you please tell me how to do with it？

**Comment by pmrowla** [comment]
using `lmpatch -r <exe> <directory>` will take everything from `<directory>` and patch it back into `<exe>`. So the way you normally use it is something like

```
$ lmar x -o some_dir game.exe 

# <do translation/patching on the lsb files inside some_dir>

$ lmpatch -r game.exe some_dir
```

This will replace every file `game.exe` with the current version from `some_dir`. So if you have any patched lsb's inside `some_dir` they will replace the original versions in `game.exe`.

Note that lmpatch will skip files/dirs in `some_dir` that didn't already exist inside `game.exe`, so it is safe to have other text/csv/backup/whatever files inside `some_dir` that you might have been using for translation/patching purposes

**Comment by yurilove** [comment]
Thank you very much for your email！
I have another question now.
I'm trying to edit the choices in game.And I used‘lmlsb edit 00000046.lsb 44’,it turns out to something like ‘Array variable’and‘Array entry’.But I don't know their meaning.
If you can provide me with some examples about them,I'd greatly appreciate!(I'm sorry that I'm not good at programming.)

**Comment by pmrowla** [comment]
The easiest way to edit in game menu choices is using the CSV method. I forgot to add it to the docs, but it works the same way as this example: https://pylivemaker.readthedocs.io/en/latest/usage.html#patching-example (just with `extractmenu`/`insertmenu` instead of `extractcsv`/`insertcsv`)

so to edit menus in 00000001.lsb you would do:

1. extract menus from LSB to CSV
```
$ lmlsb extractcsv --encoding=utf-8-sig 00000001.lsb 00000001.csv
```
2. open the csv file in your preferred spreadsheet tool (excel, google docs, etc), fill in the "Translated text" column with the text you want and save the csv
3. patch the translated CSV back into the LSB
```
$ lmlsb insertmenu --encoding=utf-8-sig 00000001.lsb 00000001.csv
```

**Comment by pmrowla** [comment]
to handle multiple menus from several LSBs at once, you can do it via batch scripting - see this thread for examples: https://github.com/pmrowla/pylivemaker/issues/58#issuecomment-626787758

**Comment by yurilove** [comment]
O

> to handle multiple menus from several LSBs at once, you can do it via batch scripting - see this thread for examples: [#58 (comment)](https://github.com/pmrowla/pylivemaker/issues/58#issuecomment-626787758)

Oh,I see!Thank you very much！
