### ISSUE TITLE
Need Translation HELP PLz

### ISSUE THREAD

**Issue by xenei** [pmrowla/pylivemaker#83]
* pylivemaker version: stable
* Python version: 3.8.9
* Operating System: Windows
* LiveMaker game: 3
Hello pmrowla,
 I need your help on how do I change character names in-game, this is my first time hacking Livemaker engine so I have no idea how to. I can translate but can't change character names Also can you send me BMPTOGALE.exe, I wasn't able to find that on the internet... please help and thank you.

**Comment by pmrowla** [comment]
For character names it depends on the game. In most cases that I've seen character names are just included in-line with the rest of the text script, but there is also a name/speaker tag that a few games actually use. You'll have to figure it out yourself by dumping/inspecting the .lsb files from your game. It's also possible that the character names are images which would need to be edited and replaced.

bmptogale is included with Livemaker itself (the actual game-making program), the final release of LM is available here: https://www.freem.ne.jp/win/game/17143 (in japanese). The original docs are included with LM, but I also mirror them here: https://pylivemaker.readthedocs.io/en/latest/_static/LiveNovel/ (also in japanese)

There's also another program called Gale which can be used instead of bmptogale (see https://github.com/pmrowla/pylivemaker/issues/65#issuecomment-635161924)

**Comment by pmrowla** [comment]
Closing this since I don't/can't help with specific translations. If you run into any actual technical issues/bugs with getting pylm to work with your particular game feel free to re-open it.

**Comment by xenei** [comment]
thank you I have resolved my issue.
